const nodemailer = require('nodemailer');

const sendVerificationEmail = async (email, verificationToken) => {
  return new Promise((resolve, reject) => {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: 'doodooapp.dev@gmail.com',
        pass: 'wbnj aser dala fpxx',
      },
    });

    const mailOptions = {
      from: 'doodooapp.dev@gmail.com',
      to: email,
      subject: 'Email Verification',
      html: `<p>Click the following link to verify your email: <a href="http://localhost:3000/verify/${verificationToken}">Verify Email</a></p><p><i>This is an autogenerated email, you don't need to reply.</i></p>`,
    };

    transporter.sendMail(mailOptions, (err, info) => {
      if (err) {
        console.error(`Error sending verification email: ${err}`);
        reject(err);
      }

      console.log(`Verification email sent: ${info.response}`);
      resolve(true);
    });
  });
};

module.exports = { sendVerificationEmail };
